# Generated by Django 4.0.5 on 2022-06-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('cover_pic_url', models.CharField(max_length=1000)),
                ('total_episodes', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
